# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee2279390c3f4d69c8985e4320a5de101d7c8362f8f2b0ecf351ae454a1817983676690ad991181d94c941c3357b98a0658efdfa2050b371c6df4d557c13ac8

test:
  secret_key_base: 68c267c04ce980eb8fa422c7aaf0b0bcd9cf9dc890b9219e540bbda471175f018e66098818de12d4a3cb7584f12f2d132f4e7337d11ef2a18d668fe1a67d162c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
